CREATE TABLE faculty (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
faculty_name VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE groups (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
group_name VARCHAR(255) NOT NULL,
faculty_id SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (faculty_id) REFERENCES faculty(id)
) ENGINE = InnoDB;

CREATE TABLE shelves (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
shelve VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE students (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
home_phone VARCHAR(255) NOT NULL,
faculty_id SMALLINT UNSIGNED NOT NULL,
group_id SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (faculty_id) REFERENCES faculty(id),
FOREIGN KEY (group_id) REFERENCES groups(id)
) ENGINE = InnoDB;

CREATE TABLE books (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author VARCHAR(255) NOT NULL,
release_date VARCHAR(255) NOT NULL,
shelve_id SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (shelve_id) REFERENCES shelves(id)
) ENGINE = InnoDB;

CREATE TABLE students_owe_books (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
student_id SMALLINT UNSIGNED NOT NULL,
book_id SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (student_id) REFERENCES students(id),
FOREIGN KEY (book_id) REFERENCES books(id)
) ENGINE = InnoDB;

CREATE TABLE users (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
hash_pass VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
